---
title: "MDS_521_lab4_presentation"
format: revealjs
editor: visual
---

# Section 1

## Welcome to my presentation

This is a quick introduction to creating a slideshow with a few illustrative examples

# Section 2

## Some very simple code

```{r}

library(lubridate)

dates <- c("1982-01-25 01:50:12",
          "1967-09-19 19:09:59",
          "1999-04-07 22:02:44",
          "2050-12-15 03:24:38",
          "2020-01-31 11:59:59",
          "2009-01-31 01:32:05",
          "2010-01-31 23:03:17")

days_of_week <- wday(ymd_hms(dates),label = TRUE, abbr = FALSE)

for (day in days_of_week){
  print(day)
}
```

# Section 3

## Another simple example but now with a plot!

```{r include = TRUE}
library(tidyverse)
library(palmerpenguins)


options(repr.plot.width = 7, repr.plot.height = 5)
penguins_original <- ggplot(data = penguins, mapping = aes(x = bill_length_mm, 
                                      y = body_mass_g,
                                     colour = species)) +
    geom_point(size = 2) +
    xlab("Bill length (mm)") +
    ylab("Body mass (g)") +
    theme_bw() +
    theme(text = element_text(size = 18))
penguins_original
```

# Section 4

## Thanks for stopping by!

I hope this very quick example gives you a good idea of all the wonderful possibilities using Quarto!
